// Research-backed pairing impact weights
// Holmstrom-Milgrom (1991): measurability gap amplifies misalignment
// Kerr (1975): rewarding A while hoping for B — worst when inversion is direct
// Moral hazard > adverse selection > information asymmetry in damage speed
const RULES=[
  // AE/CS — classic moral hazard, measurable close vs diffuse retention. Weight 3 (H-M direct application)
  {a:'ae',b:'cs',pw:3,aM:['New logo bookings','Win rate','Time to close','Quota attainment'],bM:['NRR','Churn rate','Health score'],label:"Sales closes deals CS can't retain",type:'inversion',owner:'CRO / Revenue leadership',rootCause:'AE comp rewards close, not customer lifetime value. No shared metric between sales and CS.',fix:'Introduce clawback on commission for deals churning within 6 months. Add NRR to AE variable comp at 10-15% weighting.',good:'AEs self-qualify based on fit, not just willingness to sign.'},
  {a:'ae',b:'cs',pw:3,aM:['ACV','Pipeline coverage'],bM:['Expansion ARR','Time to value'],label:'Revenue recognised at close, not value delivery',type:'ownership',owner:'CRO + CS leadership',rootCause:'Finance and sales treat contract signature as success. CS measured on outcomes they did not control.',fix:'Gate a portion of AE commission on 90-day customer health score. Align CS onboarding SLA to deal size.',good:'CS consistently hits time-to-value targets because AEs set realistic expectations.'},
  // AE/Product — moral hazard + information asymmetry combined. Weight 3
  {a:'ae',b:'product',pw:3,aM:['New logo bookings','Win rate','Quota attainment'],bM:['Roadmap adherence','Features shipped'],label:'Sales promises features not on the roadmap',type:'inversion',owner:'CEO / CRO + CPO jointly',rootCause:'No formal process to validate feature commitments before close. Product has no visibility into what is being promised.',fix:'Require Product sign-off on custom roadmap commitments above a defined ACV threshold. Log all commitments in CRM.',good:'Product is aware of all feature commitments before contracts are signed.'},
  // AE/Marketing — adverse selection, MQL quality hard to measure at creation. Weight 2
  {a:'ae',b:'marketing',pw:2,aM:['Win rate','Pipeline coverage'],bM:['MQL volume','CPL'],label:'Marketing optimises for volume, sales for quality',type:'ownership',owner:'CMO + CRO',rootCause:'Marketing measured on top-of-funnel, sales from mid-funnel down. No shared accountability for conversion.',fix:'Introduce a shared SQL-to-close metric. Include MQL quality in marketing OKRs alongside volume.',good:'Marketing voluntarily reduces MQL volume to improve conversion rate.'},
  {a:'marketing',b:'ae',pw:2,aM:['MQL volume','Pipeline sourced'],bM:['Win rate','Time to close'],label:'MQL-to-pipeline conversion blamed on the other team',type:'ownership',owner:'CRO + CMO',rootCause:'No agreed definition of a qualified lead. Marketing and sales define quality differently.',fix:'Co-define and document MQL/SQL criteria. Run a monthly pipeline review with both teams accountable.',good:'Both teams agree on lead quality and neither blames the other for conversion gaps.'},
  {a:'marketing',b:'ae',pw:1,aM:['CAC','CPL'],bM:['Quota attainment','ACV'],label:'CAC vs deal size creates budget tension',type:'ownership',owner:'CFO + CMO',rootCause:'Marketing budget set independently of deal economics. High CAC on low-ACV segments goes unnoticed.',fix:'Build a CAC:LTV ratio by segment. Shift spend toward segments where LTV justifies acquisition cost.',good:'Marketing spend decisions are made with LTV visibility, not just CPL.'},
  // Product/Eng — textbook multitask problem (Kerr + H-M). Weight 3
  {a:'product',b:'eng',pw:3,aM:['Features shipped','Time to market','Roadmap adherence'],bM:['Bug rate','Tech debt ratio','DORA metrics'],label:'Velocity targets trade against quality and stability',type:'inversion',owner:'CPO + CTO jointly',rootCause:'Product measured on shipping, engineering on stability. Sprint planning optimises for output not outcome.',fix:'Include bug rate and incident count in product OKRs. Allocate 20% of every sprint to tech debt by default.',good:'Features ship with agreed quality gates. Tech debt does not accumulate sprint-over-sprint.'},
  {a:'product',b:'eng',pw:3,aM:['Features shipped','DAU/MAU'],bM:['Incidents','Deployment frequency'],label:'Shipping speed measured separately from incident rate',type:'ownership',owner:'CTO',rootCause:'Post-launch stability is an engineering metric. Product has no skin in the game after launch.',fix:'Add a 30-day post-launch stability score to product success metrics. P1 incidents pause roadmap work.',good:'Product actively monitors post-launch health, not just adoption curves.'},
  // Product/Support — ownership gap. Weight 2
  {a:'product',b:'support',pw:2,aM:['Features shipped','Adoption rate'],bM:['Ticket volume','Escalation rate','Deflection rate'],label:'New features generate support load not owned by product',type:'ownership',owner:'CPO + VP Support',rootCause:'Product success measured at launch. Support cost from poor UX or missing docs falls entirely on Support.',fix:'Require a support readiness checklist before any feature ships. Track support tickets per feature post-launch.',good:'Product includes support ticket volume in feature success criteria.'},
  {a:'support',b:'product',pw:2,aM:['CSAT','First response time','Resolution rate'],bM:['Roadmap adherence','Time to market'],label:'Known bugs sit in backlog while new features ship',type:'inversion',owner:'CPO',rootCause:'Bug prioritisation competes directly with feature work. Product has no metric that penalises unresolved bugs.',fix:'Introduce a bug SLA: P1 within 24h, P2 within 2 weeks. Unresolved P1/P2 bugs block new feature releases.',good:'Support can predict bug resolution timelines. CSAT stops being dragged down by known issues.'},
  // CS/Support — ownership gap, NPS drag. Weight 2
  {a:'cs',b:'support',pw:2,aM:['NPS','NRR','Health score'],bM:['Ticket volume','First response time'],label:'CS owns NPS but cannot control support experience',type:'ownership',owner:'CCO / VP CS',rootCause:'NPS is influenced heavily by support interactions but CS and Support have separate managers.',fix:'Create a shared CSAT + NPS review between CS and Support. Add escalation rate to CS team health metrics.',good:'CS and Support review customer sentiment data together monthly.'},
  // CS/AE — lag, shows in renewal cycle. Weight 2
  {a:'cs',b:'ae',pw:2,aM:['Churn rate','Time to value','Health score'],bM:['Time to close','Quota attainment'],label:'Fast closes create slow time-to-value for CS',type:'lag',owner:'CRO + CCO',rootCause:'Speed-to-close is rewarded in sales. Downstream cost surfaces months later in CS.',fix:'Track time-to-first-value by AE. Include it in AE QBR data. CS flags deals at risk of slow TTV before they churn.',good:'AEs factor implementation complexity into deal timelines upfront.'},
  // TA/Leadership — raised to 3: headcount volatility + speed pressure = direct P&L impact
  {a:'ta',b:'leadership',pw:3,aM:['Time to fill','Pipeline volume','Cost per hire'],bM:['Headcount vs plan','EBITDA'],label:'TA measured on speed while leadership changes headcount plan',type:'inversion',owner:'CHRO + CFO',rootCause:'TA invests in pipelines against approved headcount. Finance changes plan without accounting for TA sunk cost.',fix:'Require 4-week notice before any headcount freeze or revision. TA pipeline investment treated as a budget commitment.',good:'TA is consulted before headcount plans change, not notified after.'},
  {a:'ta',b:'leadership',pw:3,aM:['Offer acceptance rate','Diversity of slate'],bM:['OKR score','Revenue vs target'],label:'Quality-of-hire not tracked against business outcomes',type:'lag',owner:'CHRO',rootCause:'TA success ends at offer acceptance. No mechanism connects hire quality to business performance.',fix:'Implement 90-day and 12-month performance reviews tied back to TA source. Report quality-of-hire by recruiter.',good:'TA optimises sourcing based on downstream performance data, not just fill rate.'},
  // TA/People — raised to 2: early attrition from speed hiring well documented
  {a:'ta',b:'people',pw:2,aM:['Time to fill','Quality of hire'],bM:['Attrition rate','Time to productivity'],label:'TA success measured at offer, not 90-day retention',type:'lag',owner:'CHRO',rootCause:'TA closes at offer. Attrition within 90 days is treated as a People problem, not a hiring quality signal.',fix:'Track 90-day attrition by TA source and hiring manager. Include early attrition in TA performance metrics.',good:'TA and People review early attrition data together and adjust hiring criteria accordingly.'},
  // TA/Engineering — speed hiring into technical roles compounds debt. Weight 2
  {a:'ta',b:'eng',pw:2,aM:['Time to fill','Cost per hire'],bM:['Bug rate','Tech debt ratio','DORA metrics'],label:'Speed hiring into engineering degrades technical quality',type:'lag',owner:'CTO + CHRO',rootCause:'Time-to-fill pressure reduces rigour in technical screening. Under-assessed engineers increase bug rate and tech debt over time.',fix:'Define minimum technical bar for engineering roles that cannot be waived under hiring pressure. Include 90-day quality metrics in TA reporting.',good:'Engineering hire quality is tracked and reported alongside velocity and bug rate.'},
  // TA/AE — speed hiring into quota roles inflates ramp time. Weight 2
  {a:'ta',b:'ae',pw:2,aM:['Time to fill','Offer acceptance rate'],bM:['Win rate','Quota attainment','Time to close'],label:'Speed hiring into sales inflates ramp time and drags win rate',type:'lag',owner:'CRO + CHRO',rootCause:'Offer acceptance rate rewards closing candidates quickly, not hiring the right ones. Mis-hires in quota-carrying roles take 6-9 months to surface.',fix:'Add 90-day and 6-month quota attainment to TA reporting by role. Weight candidate quality over speed in sales hiring process.',good:'Sales ramp time is predictable and TA is accountable for hire quality, not just fill rate.'},
  {a:'ta',b:'ae',pw:3,aM:['Time to fill','Pipeline volume'],bM:['New logo bookings','Pipeline coverage','Quota attainment'],label:'Open headcount in Sales creates a capacity gap TA is not measured against',type:'lag',owner:'CRO + CHRO',rootCause:'TA is measured from role approval to offer acceptance — not on the revenue impact of seats sitting empty. A 90-day fill on a quota-carrying role is a silent capacity gap that shows up in Sales results, not TA metrics.',fix:'Track open quota-carrying roles as a revenue risk item in CRO/CHRO joint reporting. Set faster fill SLAs for revenue-critical roles. Include headcount capacity in pipeline coverage calculations.',good:'Open AE roles appear in pipeline coverage forecasts, not just a hiring tracker. TA is held to revenue-weighted SLAs on quota-carrying positions.'},
  // TA/CS — volume hiring into CS without quality gates increases churn exposure. Weight 2
  {a:'ta',b:'cs',pw:2,aM:['Time to fill','Pipeline volume'],bM:['NRR','Churn rate','Health score'],label:'Volume hiring into CS without quality gates increases churn exposure',type:'lag',owner:'CCO + CHRO',rootCause:'CS hiring prioritises speed to meet headcount plan. Poor-fit CS hires struggle to manage complex accounts, accelerating churn.',fix:'Define CS hire profile by account complexity. Track 90-day NRR impact by CS cohort hired under different TA conditions.',good:'CS headcount quality is a leading indicator for NRR, not a lagging cost line.'},
  // Leadership/People — lag, compounds over time. Weight 2
  {a:'leadership',b:'people',pw:2,aM:['OKR score','Revenue vs target'],bM:['eNPS','Engagement score','Attrition rate'],label:'OKR scores stay green while engagement quietly erodes',type:'lag',owner:'CEO + CHRO',rootCause:'Engagement and attrition are lagging indicators. Damage is done before the data shows it.',fix:'Add eNPS and regrettable attrition to leadership-level OKRs. Review engagement data in every leadership QBR.',good:'Leadership treats a falling eNPS with the same urgency as a falling NRR.'},
  // Leadership/Eng — lag between revenue decisions and tech debt. Weight 2
  {a:'leadership',b:'eng',pw:2,aM:['Revenue vs target','Burn multiple'],bM:['Tech debt ratio','DORA metrics'],label:'Short-term revenue focus accelerates technical debt',type:'lag',owner:'CEO + CTO',rootCause:'Revenue pressure leads to shortcuts. Tech debt cost is invisible in short-term financials.',fix:'Include tech debt ratio in engineering OKRs reviewed by the board. Quantify debt as engineering cost per quarter.',good:'Leadership understands the revenue cost of tech debt and funds remediation proactively.'},
  // People/Leadership — lag. Weight 2
  {a:'people',b:'leadership',pw:2,aM:['eNPS','Engagement score','Attrition rate'],bM:['Headcount vs plan','EBITDA'],label:'People metrics lag - attrition visible only after it spikes',type:'lag',owner:'CHRO + CFO',rootCause:'People metrics reported separately from financial metrics. Leadership sees cost, not the leading indicators.',fix:'Build a people cost model: cost of attrition per role, cost of disengagement. Present alongside EBITDA in board packs.',good:'CFO can quantify the financial cost of a 1pt drop in eNPS.'},
  {a:'marketing',b:'product',pw:2,aM:['MQL volume','Pipeline sourced','Brand metrics'],bM:['Features shipped','Roadmap adherence','Adoption rate'],label:'Marketing campaigns ahead of product capability',type:'inversion',owner:'CMO + CPO',rootCause:'Marketing builds campaigns around future roadmap items with no sign-off gate from Product before launch.',fix:'Require Product approval for any campaign referencing upcoming features. Add a roadmap-campaign dependency tracker.',good:'Marketing only campaigns on shipped, GA features.'},
  {a:'eng',b:'cs',pw:2,aM:['Deployment frequency','Velocity','DORA metrics'],bM:['NRR','Health score','Churn rate'],label:'Engineering deployment pace not linked to CS incident load',type:'ownership',owner:'CTO + CCO',rootCause:'Engineering success measured on speed. CS bears the NRR and relationship cost of incidents triggered by fast deploys without adequate stability gates.',fix:'Add post-deploy incident rate to engineering OKRs. Gate deployment frequency targets on a 48h stability window.',good:'CS incident volume stays flat as deployment frequency increases.'},
  {a:'marketing',b:'cs',pw:2,aM:['MQL volume','CAC','CPL','Pipeline sourced'],bM:['Churn rate','NRR','Time to value'],label:'Poor-fit leads convert but churn, cost invisible to marketing',type:'lag',owner:'CMO + CCO',rootCause:'Marketing CAC measured at acquisition. ICP misfit only surfaces 6-12 months later as churn in CS data that marketing never sees.',fix:'Build cohort analysis: track NRR and 12-month churn by marketing source channel. Include downstream retention in marketing attribution model.',good:'Marketing optimises for 12-month LTV by source, not just CPL or pipeline volume.'},
  {a:'support',b:'ta',pw:2,aM:['Ticket volume','First response time','CSAT'],bM:['Time to fill','Pipeline volume','Cost per hire'],label:'Support ticket spikes drive reactive TA without fixing root causes',type:'ownership',owner:'VP Support + CHRO',rootCause:'Support SLA pressure leads to emergency headcount requests. TA fills roles fast without diagnosing whether the volume issue is a product, process, or people problem.',fix:'Require a root cause review before any reactive support hire. Track ticket-per-head ratio over time to distinguish a staffing problem from a product one.',good:'Support headcount decisions are made against a product/process fix roadmap, not just queue depth.'},
  {a:'people',b:'eng',pw:2,aM:['eNPS','Attrition rate','Engagement score'],bM:['Velocity','Bug rate','Tech debt ratio','DORA metrics'],label:'Engineering attrition drags delivery quality before it shows in metrics',type:'lag',owner:'CTO + CHRO',rootCause:'People reports attrition as an HR metric. Engineering does not model the velocity and quality cost of losing senior engineers until output visibly degrades.',fix:'Track velocity and bug rate by team tenure cohort. Model the delivery cost of each senior engineer departure and present it alongside headcount data.',good:'CTO can quantify the delivery cost of a 10% attrition rate in engineering.'},
  {a:'leadership',b:'ae',pw:2,aM:['Revenue vs target','OKR score','EBITDA'],bM:['Win rate','ACV','Quota attainment','Time to close'],label:'End-of-quarter revenue pressure drives discounting and margin erosion',type:'inversion',owner:'CEO + CRO',rootCause:'Leadership revenue targets create Q-end pressure that flows directly to AEs as discount approval urgency. No mechanism caps the margin impact of attainment pressure.',fix:'Set floor margins by deal size that cannot be overridden at quarter-end. Track discount rate vs. quarter-end timing as a pattern in CRM.',good:'Win rate and ACV hold consistent across the quarter with no Q-end spike in discounting.'},
  {a:'marketing',b:'support',pw:2,aM:['Brand metrics','MQL volume','Pipeline sourced'],bM:['CSAT','Escalation rate','First response time'],label:'Brand narrative creates expectations support cannot consistently meet',type:'inversion',owner:'CMO + VP Support',rootCause:'Marketing builds brand narrative around aspirational customer experience. Support measures reality. The gap between promise and delivery shows up in CSAT and escalation data.',fix:'Include support CSAT trend in CMO reporting. Run quarterly alignment sessions between brand messaging and observed support reality.',good:'Marketing messaging is calibrated against support satisfaction data, not just market research.'},
  {a:'product',b:'cs',pw:2,aM:['Adoption rate','DAU/MAU','Feature usage','Features shipped'],bM:['Time to value','NRR','Health score'],label:'Product adoption metrics mask the CS effort cost of poor onboarding UX',type:'ownership',owner:'CPO + CCO',rootCause:'Product measures adoption rate post-launch. CS spends disproportionate time hand-holding customers through features with poor UX — a cost that never appears in product metrics.',fix:'Add CS-hours-per-feature as a product success metric. Track time-to-first-value by feature cohort and include it in post-launch reviews.',good:'Product uses CS onboarding effort as a UX quality signal alongside adoption rate.'},
  // Finance conflicts
  {a:'finance',b:'ae',pw:2,aM:['Burn rate / runway','Gross margin','Budget vs actual'],bM:['New logo bookings','Quota attainment','ACV'],label:'Discount controls tighten as Sales discounts to hit quota',type:'inversion',owner:'CFO + CRO',rootCause:'Finance optimises for margin and burn; Sales discounts aggressively at quarter-end to close. The cost of each deal is invisible to the rep until Finance tightens controls — by which point margin has already eroded.',fix:'Set floor margins by deal size that require CFO approval to override. Track discount rate vs. quarter-end timing in CRM. Include gross margin per deal in AE comp calculations.',good:'AEs understand the margin floor before entering negotiations. Discount approvals are exceptions, not a routine quarter-end process.'},
  {a:'finance',b:'marketing',pw:2,aM:['Budget vs actual','Burn rate / runway','Headcount efficiency'],bM:['MQL volume','CAC','Pipeline sourced'],label:'Budget cuts hit marketing spend when pipeline is already thin',type:'inversion',owner:'CFO + CMO',rootCause:'Finance cuts discretionary spend when burn is high — marketing budgets are the first to move. But pipeline lags spend by 60–90 days, so cuts made in Q2 show up as a pipeline gap in Q3.',fix:'Model pipeline impact of any marketing budget cut with a 90-day lag built in. Require CFO + CRO sign-off on in-quarter marketing cuts above a threshold percentage.',good:'Finance models the pipeline impact of budget cuts before approving them. Marketing spend is treated as a pipeline investment, not a discretionary cost.'},
  {a:'finance',b:'product',pw:2,aM:['Headcount efficiency','Budget vs actual','Payback period'],bM:['Features shipped','Roadmap adherence','Adoption rate'],label:'Headcount freezes stall Product roadmap without changing commitments',type:'ownership',owner:'CFO + CPO',rootCause:'Finance controls headcount approval; Product owns roadmap commitments. When hiring freezes, roadmap dates stay — creating a delivery gap that neither team fully owns and both teams explain away.',fix:'Require CFO and CPO joint sign-off before any product team headcount freeze. Automate a roadmap revision process triggered by any freeze that flags customer commitments at risk.',good:'Roadmap commitments adjust in real time when headcount plans change. No delivery gap goes unexplained or absorbed silently by the team.'},
  {a:'finance',b:'eng',pw:2,aM:['Headcount efficiency','EBITDA','Budget vs actual'],bM:['Velocity','Tech debt ratio','Deployment frequency'],label:'Efficiency targets accelerate tech debt before the cost shows up',type:'lag',owner:'CFO + CTO',rootCause:'Finance measures Engineering output against headcount cost. Pressure to do more with less typically means shortcuts on architecture and test coverage — costs that compound silently until an incident or a rewrite forces the reckoning.',fix:'Quantify tech debt as an engineering cost per quarter. Include debt ratio in Engineering OKRs reviewed at board level. Require Finance to model the incident/rewrite cost before approving headcount reductions in Engineering.',good:'Finance understands the compound cost of tech debt and funds remediation as an investment, not overhead.'},
  {a:'finance',b:'ae',pw:2,aM:['Forecast accuracy'],bM:['Pipeline coverage','Quota attainment','Time to close'],label:'Sales pipeline inflation distorts Finance forecasts — creating a cycle of missed targets',type:'ownership',owner:'CFO + CRO',rootCause:'Finance builds revenue forecasts from sales pipeline data. AEs inflate pipeline coverage to meet activity targets, so the data Finance relies on is systematically optimistic. Neither team owns the accuracy gap.',fix:'Introduce a pipeline accuracy metric tracking forecast vs actual close rate by AE. Use historical conversion rates to weight pipeline rather than face value. Run joint Finance/Sales forecast reviews monthly.',good:'Finance builds a revenue forecast from pipeline data with less than 10% variance. AEs are measured on pipeline quality, not just volume.'},
  {a:'finance',b:'cs',pw:2,aM:['LTV:CAC ratio'],bM:['NRR','Churn rate','Expansion ARR'],label:'LTV:CAC targets sit in Finance but the levers are split across CS and Marketing',type:'ownership',owner:'CFO + CMO + CCO',rootCause:'Finance sets LTV:CAC targets but LTV is owned by CS (retention/expansion) and CAC is owned by Marketing. Neither team has full visibility of the ratio they are jointly responsible for. Each optimises their own metric; the composite ratio drifts.',fix:'Build a shared LTV:CAC dashboard visible to Marketing, CS, and Finance. Set joint targets by segment. Include LTV:CAC in both Marketing and CS OKRs, not just Finance reporting.',good:'Marketing and CS can both see their contribution to LTV:CAC and make decisions that improve the ratio, not just their own metric.'},
  // Security conflicts
  {a:'security',b:'eng',pw:2,aM:['Compliance score','Vulnerabilities remediated','Security incidents'],bM:['Deployment frequency','Velocity','DORA metrics'],label:'Compliance requirements slow deployment without shared accountability',type:'ownership',owner:'CISO + CTO',rootCause:'Security requires controls, approvals, and remediation that add friction to the deployment pipeline. Engineering is measured on velocity. Neither team owns the tradeoff — Security escalates risk, Engineering routes around it, and the gap widens.',fix:'Build security gates into the CI/CD pipeline as automated checks rather than manual approvals. Define a shared SLA for security review turnaround. Include security gate compliance in Engineering DORA metrics.',good:'Security reviews are automated where possible and never sit as manual blockers for more than 48 hours. Deployment frequency and compliance score trend upward together.'},
  {a:'security',b:'product',pw:2,aM:['Vulnerabilities remediated','Compliance score','Risk score'],bM:['Features shipped','Time to market','Adoption rate'],label:'Features ship under deadline pressure; security debt accumulates invisibly',type:'ownership',owner:'CPO + CISO',rootCause:'Product roadmaps rarely include security hardening as a deliverable. Under time-to-market pressure, security requirements get deferred. The debt is real but invisible until a breach or audit makes it expensive.',fix:'Require a security sign-off as part of the feature launch checklist. Include open security items in product roadmap planning. Track security debt per feature as a post-launch metric.',good:'Security requirements are scoped into features at design stage, not bolted on post-launch. No feature ships with open critical vulnerabilities.'},
  {a:'security',b:'leadership',pw:1,aM:['MTTD','MTTR','Risk score','Compliance score'],bM:['Revenue vs target','EBITDA','Burn multiple'],label:'Security investment deprioritised against growth spend until an incident forces it',type:'inversion',owner:'CEO + CISO',rootCause:'Leadership optimises for growth metrics; Security is a cost centre with no obvious revenue line. Investment is chronically underfunded relative to risk — a rational response to incentives that creates a fragile system exposed by the first serious incident.',fix:'Present risk score and MTTD/MTTR trends in leadership QBRs alongside revenue metrics. Quantify the cost of a potential breach against current security investment. Set a minimum security budget floor as a percentage of revenue.',good:'Security investment is treated as risk management, not overhead. Leadership can articulate the breach cost vs. investment tradeoff at any board meeting.'},
  {a:'security',b:'eng',pw:2,aM:['Patch coverage'],bM:['Deployment frequency','Velocity','Tech debt ratio'],label:'Patch coverage targets conflict with deployment velocity — Security and Engineering optimise against each other',type:'inversion',owner:'CISO + CTO',rootCause:'Security measures patch coverage as a risk reduction metric. Engineering deployment pipelines treat patching as friction that slows velocity. Neither team has a shared metric that values both speed and coverage — the tradeoff is resolved by whoever escalates harder.',fix:'Define a patch SLA tiered by severity: critical within 48h, high within 7 days, medium within 30 days. Include critical patch coverage in engineering DORA metrics. Automate patching for lower-severity vulnerabilities to remove the velocity argument.',good:'Engineering and Security share a dashboard where patch coverage and deployment frequency are both visible. Critical patch SLAs are met without impacting deployment targets.'},
  // Marketing
  {a:'marketing',b:'ae',pw:2,aM:['MQL-to-opp rate'],bM:['Pipeline coverage','Win rate','Time to close'],label:'MQL-to-opp conversion is a shared metric neither team fully owns',type:'ownership',owner:'CRO + CMO',rootCause:'Marketing is measured on MQL-to-opp conversion but AEs control follow-up speed, prioritisation, and qualification rigour. When the rate drops, both teams have plausible explanations that point at the other.',fix:'Define a shared SLA: MQLs must be actioned within 24 hours. Track speed-to-first-contact by AE alongside MQL quality scores from Marketing. Hold both accountable in a monthly revenue review.',good:'Marketing and Sales agree on what a qualified lead looks like and can jointly diagnose conversion gaps without attributing blame.'},
  // People / HR
  {a:'people',b:'leadership',pw:2,aM:['Promotion rate'],bM:['EBITDA','Headcount vs plan','Burn multiple'],label:'Promotion freezes driven by financial pressure undermine talent retention — the cost arrives 12 months later',type:'inversion',owner:'CEO + CHRO + CFO',rootCause:'People teams build promotion cadences as a retention and recognition lever. When leadership freezes promotions to manage EBITDA or headcount costs, the signal to high performers is immediate — but the attrition cost arrives 6-12 months later, long after the budget cycle that caused it.',fix:'Model the cost of losing a senior performer vs the cost of a promotion before freezing cycles. Include promotion rate in People OKRs with a floor below which leadership must actively decide to break.',good:'Leadership makes promotion freeze decisions with the full attrition cost modelled, not just the headcount saving.'},
  {a:'people',b:'eng',pw:1,aM:['Training completion'],bM:['Velocity','Bug rate','DORA metrics'],label:'Engineering training deprioritised under velocity pressure — quality debt accumulates in the team, not the codebase',type:'lag',owner:'CTO + CHRO',rootCause:'People measures training completion as a compliance and development metric. Engineering managers deprioritise it when sprint velocity is under pressure. The quality and security gap this creates is invisible until it surfaces as incidents, bugs, or attrition of the people who knew what they were doing.',fix:'Protect a minimum training allocation per engineer per quarter that cannot be traded against sprint velocity. Track training completion by team and include it in engineering health metrics reviewed by the CTO.',good:'Training completion is treated as an investment in engineering quality, not a nice-to-have that yields to delivery pressure.'},
  // AE/People — sales attrition is one of the most expensive patterns in SaaS
  {a:'ae',b:'people',pw:2,aM:['Quota attainment','New logo bookings','Win rate'],bM:['Attrition rate','eNPS','Engagement score'],label:'Quota pressure drives sales attrition that neither team is measured against preventing',type:'inversion',owner:'CRO + CHRO',rootCause:'AE comp maximises individual revenue output. People tracks attrition as a lagging HR metric. No shared mechanism connects quota design to the burnout and attrition it produces — the CRO sees a pipeline gap, not a people problem.',fix:'Model the full cost of AE attrition: ramp time, deal disruption, recruitment cost. Include regrettable sales attrition as a CRO metric alongside quota attainment. Review quota design in partnership with People, not just Finance.',good:'CRO and CHRO jointly own a sales attrition target. Quota design decisions include a modelled attrition risk, not just a revenue projection.'},
  // CS/Finance — classic underinvestment trap with NRR consequence
  {a:'cs',b:'finance',pw:2,aM:['NRR','Churn rate','Health score','Time to value'],bM:['Budget vs actual','Headcount efficiency','EBITDA'],label:'CS headcount is cut as a cost line; the NRR consequence arrives the following quarter',type:'lag',owner:'CFO + CCO',rootCause:'Finance views CS as a cost centre and optimises headcount efficiency against it. CS argues headcount is a retention investment, but cannot always demonstrate the causal link in time to prevent cuts. The NRR impact surfaces 1-2 quarters after the decision.',fix:'Build a CS capacity model that maps CSM-to-account ratios against NRR outcomes by cohort. Present the model to Finance before any CS headcount decision. Set a minimum coverage ratio below which churn risk is formally logged.',good:'Finance understands the NRR value of CS headcount before approving reductions. Cuts below a defined coverage ratio require CEO sign-off.'},
  // Leadership/CS — NRR visibility gap
  {a:'leadership',b:'cs',pw:2,aM:['Revenue vs target','NRR','Burn multiple'],bM:['Health score','Time to value','Churn rate'],label:"Leadership tracks NRR at the top line but can't see the CS team signals that predict it 90 days out",type:'lag',owner:'CEO + CCO',rootCause:'Leadership reviews NRR as a board metric but CS team-level leading indicators — health scores, time-to-value, escalation trends — sit in CS tools that leadership rarely accesses. By the time NRR moves, the causal window for intervention has closed.',fix:'Add CS health score and at-risk account count to the monthly leadership dashboard alongside NRR. Set an escalation protocol: if health scores drop below a threshold, it triggers a leadership review before it hits the NRR line.',good:'Leadership can predict NRR movement 60-90 days in advance from CS health data. Intervention happens before churn, not after.'},
];
